const BingoData: BingoItem[] = [
  {
    id: 1,
    icon: 'icon',
    description: 'description1',
    isComplete: false,
  },
  {
    id: 2,
    icon: 'icon',
    description: 'description2',
    isComplete: false,
  },
  {
    id: 3,
    icon: 'icon',
    description: 'description3',
    isComplete: false,
  },
  {
    id: 4,
    icon: 'icon',
    description: 'description4',
    isComplete: false,
  },
  {
    id: 5,
    icon: 'icon',
    description: 'description5',
    isComplete: false,
  },
  {
    id: 6,
    icon: 'icon',
    description: 'description6',
    isComplete: false,
  },
  {
    id: 7,
    icon: 'icon',
    description: 'description7',
    isComplete: false,
  },
  {
    id: 8,
    icon: 'icon',
    description: 'description8',
    isComplete: false,
  },
  {
    id: 9,
    icon: 'icon',
    description: 'description9',
    isComplete: false,
  },
  {
    id: 10,
    icon: 'icon',
    description: 'description10',
    isComplete: false,
  },
  {
    id: 11,
    icon: 'icon',
    description: 'description11',
    isComplete: false,
  },
  {
    id: 12,
    icon: 'icon',
    description: 'description12',
    isComplete: false,
  },
  {
    id: 13,
    icon: 'icon',
    description: 'description13',
    isComplete: false,
  },
  {
    id: 14,
    icon: 'icon',
    description: 'description14',
    isComplete: false,
  },
  {
    id: 15,
    icon: 'icon',
    description: 'description15',
    isComplete: false,
  },
  {
    id: 16,
    icon: 'icon',
    description: 'description16',
    isComplete: false,
  },
  {
    id: 17,
    icon: 'icon',
    description: 'description17',
    isComplete: false,
  },
  {
    id: 18,
    icon: 'icon',
    description: 'description18',
    isComplete: false,
  },
  {
    id: 19,
    icon: 'icon',
    description: 'description19',
    isComplete: false,
  },
  {
    id: 20,
    icon: 'icon',
    description: 'description20',
    isComplete: false,
  },
  {
    id: 21,
    icon: 'icon',
    description: 'description21',
    isComplete: false,
  },
  {
    id: 22,
    icon: 'icon',
    description: 'description22',
    isComplete: false,
  },
  {
    id: 23,
    icon: 'icon',
    description: 'description23',
    isComplete: false,
  },
  {
    id: 24,
    icon: 'icon',
    description: 'description24',
    isComplete: false,
  },
  {
    id: 25,
    icon: 'icon',
    description: 'description25',
    isComplete: false,
  },
];

export default BingoData;