const BingoData: BingoItem[] = [
  {
    id: 1,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 2,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 3,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 4,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 5,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 6,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 7,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 8,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 9,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 10,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 11,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 12,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 13,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 14,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 15,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 16,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 17,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 18,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 19,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 20,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 21,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 22,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 23,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 24,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
  {
    id: 25,
    isComplete: false,
    isBingo: false,
    memberWhoCompletes: undefined,
  },
];

export default BingoData;